defaults: &defaults
  working_directory: /home/nerves/build
  docker:
    - image: nervesproject/toolchains

build: &build
  resource_class: large
  steps:
    - checkout
    - restore_cache:
        key: nerves/downloads/{{ .Environment.TOOLCHAIN }}/{{ .Environment.HOST_ARCH }}
    - run:
        name: Update Path
        command: |
          echo 'export PATH=$HOME/build/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: Fetch Dependencies
        command: git clone git://github.com/raspberrypi/tools.git
    - run:
        name: Build
        command: ./nerves_toolchain_ctng/build.sh $TOOLCHAIN
    - save_cache:
        key: nerves/downloads/{{ .Environment.TOOLCHAIN }}/{{ .Environment.HOST_ARCH }}
        paths:
          - "/home/nerves/build/dl"
    - run:
        name: "Create artifact dir"
        command: mkdir -p /home/nerves/deploy/toolchain
    - run:
        name: "Copy Artifacts"
        command: cp ${TOOLCHAIN}*.tar.xz /home/nerves/deploy/toolchain
    - store_artifacts:
        path: /home/nerves/deploy/toolchain
        destination: toolchain
    - save_cache:
        key: nerves/build/{{ .Environment.TOOLCHAIN }}-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
        paths:
          - "/home/nerves/build"
    - save_cache:
        key: nerves/deploy/{{ .Environment.TOOLCHAIN }}-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
        paths:
          - "/home/nerves/deploy/toolchain"

build_workflow: &build_workflow
  context: org-global
  filters:
    tags:
      only: /.*/

deploy_workflow: &deploy_workflow
  context: org-global
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /v.*/

canadian_rpi: &canadian_rpi
  HOST_OS: linux
  HOST_ARCH: arm

version: 2.0

jobs:
  #-------------------------------
  # aarch64_unknown_linux_gnueabi
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_aarch64_unknown_linux_gnueabi:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_aarch64_unknown_linux_gnueabi
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_aarch64_unknown_linux_gnueabi:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_aarch64_unknown_linux_gnueabi
      <<: *canadian_rpi
    <<: *build
  
  #-------------------------------
  # arm_unknown_linux_gnueabihf
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_arm_unknown_linux_gnueabihf:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_arm_unknown_linux_gnueabihf
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_arm_unknown_linux_gnueabihf:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_arm_unknown_linux_gnueabihf
      <<: *canadian_rpi
    <<: *build

  #-------------------------------
  # armv5tejl_unknown_linux_musleabi
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_armv5tejl_unknown_linux_musleabi:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_armv5tejl_unknown_linux_musleabi
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_armv5tejl_unknown_linux_musleabi:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_armv5tejl_unknown_linux_musleabi
      <<: *canadian_rpi
    <<: *build

  #-------------------------------
  # armv6_rpi_linux_gnueabi
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_armv6_rpi_linux_gnueabi:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_armv6_rpi_linux_gnueabi
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_armv6_rpi_linux_gnueabi:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_armv6_rpi_linux_gnueabi
      <<: *canadian_rpi
    <<: *build

  #-------------------------------
  # i586_unknown_linux_gnu
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_i586_unknown_linux_gnu:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_i586_unknown_linux_gnu
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_i586_unknown_linux_gnu:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_i586_unknown_linux_gnu
      <<: *canadian_rpi
    <<: *build

  #-------------------------------
  # mipsel_unknown_linux_musl
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_mipsel_unknown_linux_musl:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_mipsel_unknown_linux_musl
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_mipsel_unknown_linux_musl:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_mipsel_unknown_linux_musl
      <<: *canadian_rpi
    <<: *build

  #-------------------------------
  # x86_64_unknown_linux_gnu
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_x86_64_unknown_linux_gnu:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_x86_64_unknown_linux_gnu
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_x86_64_unknown_linux_gnu:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_x86_64_unknown_linux_gnu
      <<: *canadian_rpi
    <<: *build

  #-------------------------------
  # x86_64_unknown_linux_musl
  #-------------------------------
  # build
  #  linux
  build_linux_nerves_toolchain_x86_64_unknown_linux_musl:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_x86_64_unknown_linux_musl
    <<: *build
  #  rpi
  build_rpi_nerves_toolchain_x86_64_unknown_linux_musl:
    <<: *defaults
    environment:
      TOOLCHAIN: nerves_toolchain_x86_64_unknown_linux_musl
      <<: *canadian_rpi
    <<: *build
  
  deploy:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Create Artifacts Dir
        command: mkdir -p /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_aarch64_unknown_linux_gnueabi-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_arm_unknown_linux_gnueabihf-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_armv5tejl_unknown_linux_musleabi-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_armv6_rpi_linux_gnueabi-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_i586_unknown_linux_gnu-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_mipsel_unknown_linux_musl-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_x86_64_unknown_linux_gnu-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - restore_cache:
        key: nerves/deploy/nerves_toolchain_x86_64_unknown_linux_musl-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
    - run:
        name: Copy Artifact
        command: cp /home/nerves/deploy/toolchain/*.tar.xz /home/nerves/deploy/artifacts
    - run:
        name: Install dependencies
        command: |
          wget https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
          unzip ghr_v0.5.4_linux_amd64.zip
    - run:
        name: "Create Release Notes"
        command: grep -Pazo "(?s)(?<=## ${CIRCLE_TAG})[^#]+" ./CHANGELOG.md > /nerves/deploy/RELEASE_NOTES
    - run:
        name: Deploy artifacts to Github
        command: ./ghr -draft -t $GITHUB_TOKEN -u nerves-project -r $CIRCLE_PROJECT_REPONAME -b "$(cat /nerves/deploy/system/RELEASE_NOTES)" $CIRCLE_TAG /home/nerves/deploy/artifacts

workflows:
  version: 2
  build_deploy:
    jobs:
      #-------------------------------
      # aarch64_unknown_linux_gnueabi
      #-------------------------------
      - build_linux_nerves_toolchain_aarch64_unknown_linux_gnueabi:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_aarch64_unknown_linux_gnueabi:
          <<: *build_workflow
            
      #-------------------------------
      # arm_unknown_linux_gnueabihf
      #-------------------------------
      - build_linux_nerves_toolchain_arm_unknown_linux_gnueabihf:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_arm_unknown_linux_gnueabihf:
          <<: *build_workflow

      #-------------------------------
      # armv5tejl_unknown_linux_musleabi
      #-------------------------------
      - build_linux_nerves_toolchain_armv5tejl_unknown_linux_musleabi:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_armv5tejl_unknown_linux_musleabi:
          <<: *build_workflow

      #-------------------------------
      # armv6_rpi_linux_gnueabi
      #-------------------------------
      - build_linux_nerves_toolchain_armv6_rpi_linux_gnueabi:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_armv6_rpi_linux_gnueabi:
          <<: *build_workflow
            
      #-------------------------------
      # i586_unknown_linux_gnu
      #-------------------------------
      - build_linux_nerves_toolchain_i586_unknown_linux_gnu:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_i586_unknown_linux_gnu:
          <<: *build_workflow
            
      #-------------------------------
      # mipsel_unknown_linux_musl
      #-------------------------------
      - build_linux_nerves_toolchain_mipsel_unknown_linux_musl:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_mipsel_unknown_linux_musl:
          <<: *build_workflow
            
      #-------------------------------
      # x86_64_unknown_linux_gnu
      #-------------------------------
      - build_linux_nerves_toolchain_x86_64_unknown_linux_gnu:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_x86_64_unknown_linux_gnu:
          <<: *build_workflow

      #-------------------------------
      # x86_64_unknown_linux_musl
      #-------------------------------
      - build_linux_nerves_toolchain_x86_64_unknown_linux_musl:
          <<: *build_workflow
      - build_rpi_nerves_toolchain_x86_64_unknown_linux_musl:
          <<: *build_workflow
      
      #-------------------------------
      # Deploy Toolchains
      #-------------------------------
      - deploy:
          <<: *deploy_workflow
          requires:
            - build_linux_nerves_toolchain_aarch64_unknown_linux_gnueabi
            - build_rpi_nerves_toolchain_aarch64_unknown_linux_gnueabi
            - build_linux_nerves_toolchain_arm_unknown_linux_gnueabihf
            - build_rpi_nerves_toolchain_arm_unknown_linux_gnueabihf
            - build_linux_nerves_toolchain_armv5tejl_unknown_linux_musleabi
            - build_rpi_nerves_toolchain_armv5tejl_unknown_linux_musleabi
            - build_linux_nerves_toolchain_armv6_rpi_linux_gnueabi
            - build_rpi_nerves_toolchain_armv6_rpi_linux_gnueabi
            - build_linux_nerves_toolchain_i586_unknown_linux_gnu
            - build_rpi_nerves_toolchain_i586_unknown_linux_gnu
            - build_linux_nerves_toolchain_mipsel_unknown_linux_musl
            - build_rpi_nerves_toolchain_mipsel_unknown_linux_musl
            - build_linux_nerves_toolchain_x86_64_unknown_linux_gnu
            - build_rpi_nerves_toolchain_x86_64_unknown_linux_gnu
            - build_linux_nerves_toolchain_x86_64_unknown_linux_musl
            - build_rpi_nerves_toolchain_x86_64_unknown_linux_musl
